/*
 * SourceMod Entity Projects
 * by: Entity
 *
 * Copyright (C) 2020 Kőrösfalvi "Entity" Martin
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) 
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program.  If not, see <http://www.gnu.org/licenses/>.
 */
 
#if !defined _smlib_included
	#include <smlib>
#endif

#if defined _emperor_included
	#endinput
#endif
#define _emperor_included

#define EMPEROR_VERSION "0.1"

#include <emperor/clients>
#include <emperor/files>
#include <emperor/weapons>
#include <emperor/messages>
#include <emperor/variables>
#include <emperor/debug>
#include <emperor/entities>
#include <emperor/extras>